### PR TITLE
 Enable "!statg stats" and "!statg match" without registering

### LINKED ISSUE #7: Enable "!statg stats" without "!statg register"
If the user did not register itself with ```!statg register```, the discord name could be used when typing ```!statg stats``` or ```!statg match```. 

Obviously, this won't work if the discord and pubg names don't match, but would be nice for everyone else.

### PR DESCRIPTION
**Pull request by medusalix**
Let me know if you have any questions about the code 😃.

Resolves #7 

#### MatchCommandHandler

- [x] should send an api request for the match
- [x] should send a message containing the match data
- [x] ~~should send an error message if player is not registered~~
- [x] ~~should not send api request if player is not registered~~
- [x] should send an error message if no matches are inside the data array

#### StatsCommandHandler

- [x] should query the database for the region of the player
- [x] should request the seasons from pubg api after retrieving the id from db
- [x] should request the stats for the given player id and current season
- [x] should return the stats for all game modes if no argument was passed to cmd
- [x] should return avg. stats for game mode "solo" when passed as argument
- [x] should return avg. stats for game mode "solo-fpp" when passed as argument
- [x] should return avg. stats for game mode "duo" when passed as argument
- [x] should return avg. stats for game mode "duo-fpp" when passed as argument
- [x] should return avg. stats for game mode "squad" when passed as argument
- [x] should return avg. stats for game mode "squad-fpp" when passed as argument
- [x] ~~should send an error error message if there is no player id for discord user in db~~
- [x] should send an error message if an invalid argument was passed
- [x] should send an error message if multiple arguments were passed

### CODE REVIEW

**Comment by kuper-adrian** [comment]
Hey cool, thanks for your time and contributions 😄 This issue was not so easy to do.

Looks like you broke some tests though. But I can't really blame you, the tests are pretty messy and not fun to write or change at all (statg was my first "bigger" javascript project and my first time doing unit tests in js 🙈). Give me some time to look at your code and let me see what I can do about the unit tests and I will come back to you sometime soon 👍 

In the meantime, happy remaining Hacktoberfest 😉

**Comment by medusalix** [comment]
Whoops, didn't notice the tests failing 😄. Happy Hacktoberfest to you too.

**Comment by medusalix** [comment]
I fixed most of the tests by now, but there are still some pieces related to checking if the player is not registered. Those tests are not needed anymore, do you think they should be removed?

**Comment by kuper-adrian** [comment]
Dude, nice work 👍 

Sorry for being late on your pull request, but the last PUBG update not only broke the game but also the statg bot 😅 Finally found the time to look at your changes though and they look really great. I will merge your pull request after deleting the three obsolete unit tests and updating the README to reflect the changes to the `stats` and `match` commands.

**Pull request merged**
